---
# tasks file for apache2-role
- name: Install apache2
  apt: pkg={{ item }} state=present
  with_items: "{{ apache2.packages.ubuntu.focal }}"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_release == "focal"

- name: Install apache2 on Debian BullSeye - BookWorm
  apt: pkg={{ item }} state=present
  with_items: "{{ apache2.packages.debian.bullseye_bookworm }}"
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_release'] == "bulseye") or
        (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_release'] == "bookworm")

- name: Asegurarse de que apache2 esté corriendo y habilitado al inicio.
  service: name=apache2 state=started enabled=yes

#Adaptar a la nueva versión.
- name: Descomprimimos la raiz del sitio, backups
  ansible.builtin.unarchive:
    src: "{{ item.value.bk_raiz }}"
    dest: "/var/www/{{ item.value.http_host }}"
    group: "{{ app_user }}"
    owner: "{{ app_user }}"
  loop: "{{ sites_config|dict2items }}"

- name: Change the owner an permisions
  ansible.builtin.file:
    dest: "/var/www/{{ item.value.http_host }}"
    state: directory
    recurse: true
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    #Set directories to 755 and files to 644
    mode: u=rwX,g=rX,o=rX
  loop: "{{ sites_config|dict2items }}"

- name: Agregamos VirtualHost
  #Agrega los virtual Host Necesarios bansandoce en el template template/apache.conf.j2 y lo deja en /etc/apache2/site-available/default
  template:
    src=apache.conf.j2
    dest="/etc/apache2/sites-available/{{ item.value.http_conf }}"
    owner=root
    mode=0644
  loop: "{{ sites_config|dict2items }}"

- name: Habilitamos el nuevo sitio
  ansible.builtin.shell:
    cmd: "/usr/sbin/a2ensite {{ item.value.http_conf }}"
  loop: "{{ sites_config|dict2items }}"

- name: Deshabilitamos el sitio default
  ansible.builtin.shell:
    cmd: "/usr/sbin/a2dissite 000-default.conf"

  notify:
    - check apache2 config
    - restart apache2

  tags: mr-apache  
