---
# tasks file for apache2-role
- name: Install apache2
  apt: pkg={{ item }} state=present
  #Que items? selecciona los paquetes de la carpeta vars/main.yml, donde se indica apache2 y la sección de packages
  with_items: "{{ apache2.packages }}"

- name: Asegurarse de que apache2 esté corriendo y habilitado al inicio.
  service: name=apache2 state=started enabled=yes

- name: Descomprimimos la raiz del sitio, backups
  ansible.builtin.unarchive:
    src: "files/{{ bk_raiz }}"
    dest: /var/www
    group: "{{ app_user }}"
    owner: "{{ app_user }}"

- name: Agregamos VirtualHost
  #Agrega los virtual Host Necesarios bansandoce en el template template/apache.conf.j2 y lo deja en /etc/apache2/site-available/default
  template:
    src=apache.conf.j2
    dest="/etc/apache2/sites-available/{{ http_conf }}"
    owner=root
    mode=0644

- name: Habilitamos el nuevo sitio
  ansible.builtin.shell:
    cmd: "/usr/sbin/a2ensite {{ http_conf }}"

- name: Deshabilitamos el sitio default
  ansible.builtin.shell:
    cmd: "/usr/sbin/a2dissite 000-default.conf"

  notify:
    - restart apache2

  tags: apache  
