---

# tasks file for MySQL
- name: Install mysql
  apt: pkg={{ item }} state=present
  #Que items? selecciona los paquetes de la carpeta vars/main.yml, donde se indica mysql y la sección de packages
  with_items: "{{ mysql.packages }}"
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_release'] == "bulseye") or
        (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_release'] == "bookworm") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_release'] == "focal")
        
- name: Asegurarse de que mysql esté corriendo y habilitado al inicio.
  service: name=mysql state=started enabled=yes


- name: Copiamos el Bakcups de la DB.
  ansible.builtin.copy:
    src: "files/{{ item.value.wp_mysql_db }}.sql"
    dest: "/tmp/{{ item.value.wp_mysql_db }}.sql"
    mode: '0750'
  loop: "{{ sites_config|dict2items }}"
  become: yes

- name: Importamos la DB mysql
  mysql_db:
    login_user: root
    login_password: ""
    login_host: localhost
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: import
    target: "/tmp/{{ wp_mysql_db }}.sql" #Location, on the remote host, of the dump file to read from or write to.
    name: "{{ item.value.wp_mysql_db }}"
  loop: "{{ sites_config|dict2items }}"
  become: yes

- name: Creamos usuario MySql y Atorgamos todos los privilegios sobre la DB importada
  mysql_user:
    login_user: root
    login_password: ""
    login_host: localhost
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ item.value.wp_mysql_user }}"
    password: "{{ item.value.wp_mysql_password }}"
    priv: '{{ item.value.wp_mysql_db }}.*:ALL,GRANT'
    state: present
  loop: "{{ sites_config|dict2items}}"
  become: yes

  tags: mr-mysql